version: '3.9'
services:
  postgres:
    image: postgres:16.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_LOG_STATEMENTS: all
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_password}
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data